### ISSUE TITLE
tried it in v0.4

### ISSUE THREAD

**Issue by JeffreySarnoff** [REX-Computing/unumjl#1] opened 2015-10-29 23:56 UTC
I stumbled on your work-in-progress and tried it v0.4;
after correcting the warnings and a little testing, I found
    u3 = convert(Unum{4,5}, 3)
    u5 = convert(Unum{4,5}, 5)
    shouldbe15 = u3*u5
   convert(Float64, shouldbe15)
  14.0

**Comment by ityonemo** [comment] 2015-10-30 20:59
Hm.  It seems to work just fine in 3.11 - so it may make some time to figure out the problem and resolve this...  Apologies, before I move to 4.0 I'm going to finish working on a somewhat major refactoring process (you can see progress on "directory-reorg" branch)
![screenshot from 2015-10-30 13 56 21](https://cloud.githubusercontent.com/assets/1219073/10857910/5b3b8330-7f0e-11e5-9b44-49884e187bea.png)
.

**Comment by ityonemo** [comment] 2015-10-30 21:03
If you could do me a favor and run both calculate and convert at the end, also double check to see if the binary struct representations of the three values match, that would help greatly.

**Comment by JeffreySarnoff** [comment] 2015-11-01 20:09
julia> u3 = convert(Unum{4,5},3)
Unums.Unum{4,5}(0x0000,0x0000,0x0000,0x8000000000000000,0x0000000000000001)

julia> u5 = convert(Unum{4,5},5)
Unums.Unum{4,5}(0x0001,0x0001,0x0000,0x4000000000000000,0x0000000000000003)

julia> calculate(u5)
5.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> calculate(u3)
3.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> u3*u5
Unums.Unum{4,5}(0x0001,0x0002,0x0000,0xc000000000000000,0x0000000000000006)

the binary unum representations for u3,u5 match, but their product does not
(0xc000.. vs 0xe000..)

julia> u3*u7
Unums.Unum{4,5}(0x0002,0x0002,0x0000,0x2000000000000000,0x0000000000000007)
is 18.0 not 21.0

julia> u3*u6
Unums.Unum{4,5}(0x0000,0x0002,0x0000,0x0000000000000000,0x0000000000000007)
is 16.0 not 18.0

**Comment by JeffreySarnoff** [comment] 2015-11-02 01:12
also , using v3.11 (the last line should evaluate true)

julia> one=convert(Unum{3,4},1)
Unum{3,4}(0x0000,0x0001,0x0000,0x0000000000000000,0x0000000000000001)

julia> one=convert(Unum{3,4},1)
Unum{3,4}(0x0000,0x0001,0x0000,0x0000000000000000,0x0000000000000001)

julia> onehundred=convert(Unum{3,4},100)
Unum{3,4}(0x0003,0x0003,0x0000,0x9000000000000000,0x000000000000000d)

julia> eleven=convert(Unum{3,4},11)
Unum{3,4}(0x0002,0x0002,0x0000,0x6000000000000000,0x0000000000000006)

julia> tst=(1.0/100.0)/11.0
0.0009090909090909091

julia> utst=(one/onehundred)/eleven
Ubound{3,4}(Unum{3,4}(0x000f,0x0004,0x0001,0xdc9e000000000000,0x0000000000000004),Unum{3,4}(0x000f,0x0004,0x0001,0xdca0000000000000,0x0000000000000004))

julia> calculate(utst.highbound)
9.090900421142578125e-04 with 256 bits of precision

calculate(utst.highbound) >= tst
false

**Comment by ityonemo** [comment] 2015-11-02 08:25
excellent.  It appears the problem is in calculating 1/100, it outputs the ubound that is one ulp lower than the actual result, so I will need to look into why that's happening.

julia> tmp1 = one/onehundred
Unum{3,4}(0x000f,0x0004,0x0001,0x47ad000000000000,0x0000000000000008)
julia> calculate(tmp1)
9.99987125396728515625e-03 with 256 bits of precision
julia> calculate(next_exact(tmp1))
9.9999904632568359375e-03 with 256 bits of precision
julia> calculate(next_exact(next_exact(tmp1)))
1.00002288818359375e-02 with 256 bits of precision

**Comment by ityonemo** [comment] 2016-07-13 00:13
all issues fixed in current version.

**Closed as completed by ityonemo** 2016-07-13 00:13 UTC
